spring:
  application:
    name: journal
  data:
    mongodb:
      uri: mongodb+srv://193j1a05h3:ammUGsfgO9t7ABTq@cluster0.wax9p.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      database: journaldb
      auto:
        index-creation: true

  main:
    allow-circular-references: true

logging:
  level:
    org:
      springframework:
        security: DEBUG